function laminarBoundaryCalculations1 = importDepths(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  LAMINARBOUNDARYCALCULATIONS1 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  LAMINARBOUNDARYCALCULATIONS1 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  LAMINARBOUNDARYCALCULATIONS1 = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  laminarBoundaryCalculations1 = importfile("E:\formattedDataOutputs\laminarBoundaryCalculations.xlsx", "Sheet1", [2, 5]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-May-2022 11:05:56

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 5];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":M" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["session", "topOfCor", "botOfCor", "SinkBtm", "VarName5", "UpperOutBoundry", "UpperTop", "UpperBtm", "MiddleTop", "MiddleBtm", "LowerTop", "LowerBtm", "LowerOutBoundry"];
opts.VariableTypes = ["string", "double", "double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["session", "VarName5"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["session", "VarName5"], "EmptyFieldRule", "auto");

% Import the data
laminarBoundaryCalculations1 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":M" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    laminarBoundaryCalculations1 = [laminarBoundaryCalculations1; tb]; %#ok<AGROW>
end

end